// Generated by CoffeeScript 1.6.3
(function() {
  this.Instructions = (function() {
    function Instructions(callback) {
      this.callback = callback;
      this.domElement = $('#instructions');
    }

    Instructions.prototype.instructions = {
      leftclick: "Remove block",
      rightclick: "Add block",
      drag: "Drag with the left mouse clicked to move the camera",
      pause: "Pause/Unpause",
      space: "Jump",
      wasd: "WASD keys to move",
      scroll: "Scroll to change selected block"
    };

    Instructions.prototype.intructionsBody = function() {
      var _this = this;
      this.domElement.append("<div id='instructionsContent'>                                         <h1>Click to start</h1>                                         <table>" + (this.lines()) + "</table>                                         </div>");
      $("#instructionsContent").mousedown(function() {
        _this.domElement.hide();
        return _this.callback();
      });
    };

    Instructions.prototype.ribbon = function() {
      return '<a href="https://github.com/danielribeiro/WebGLCraft" target="_blank">\
                      <img style="position: fixed; top: 0; right: 0; border: 0;"\
                      src="http://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"\
                      alt="Fork me on GitHub"></a>';
    };

    Instructions.prototype.insert = function() {
      var hnimage, hnlink, legal, minecraft;
      this.setBoder();
      this.intructionsBody();
      minecraft = "<a href='http://www.minecraft.net/' target='_blank'>Minecraft</a>";
      legal = "<div>Not affiliated with Mojang. " + minecraft + " is a trademark of Mojang</div>";
      hnimage = '<img class="alignnone" title="hacker news" src="http://1.gravatar.com/blavatar/96c849b03aefaf7ef9d30158754f0019?s=20" alt="" width="20" height="20" />';
      hnlink = "<div>Comment on  " + hnimage + " <a href='http://news.ycombinator.com/item?id=3376620'  target='_blank'>Hacker News</a></div>";
      this.domElement.append(legal + hnlink + this.ribbon());
      return this.domElement.show();
    };

    Instructions.prototype.lines = function() {
      var inst, ret;
      ret = (function() {
        var _results;
        _results = [];
        for (inst in this.instructions) {
          _results.push(this.line(inst));
        }
        return _results;
      }).call(this);
      return ret.join(' ');
    };

    Instructions.prototype.line = function(name) {
      var inst;
      inst = this.instructions[name];
      return "<tr><td class='image'>" + (this.img(name)) + "</td>                      <td class='label'>" + inst + "</td></tr>";
    };

    Instructions.prototype.setBoder = function() {
      var prefix, _i, _len, _ref;
      _ref = ['-webkit-', '-moz-', '-o-', '-ms-', ''];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        prefix = _ref[_i];
        this.domElement.css(prefix + 'border-radius', '10px');
      }
    };

    Instructions.prototype.img = function(name) {
      return "<img src='./instructions/" + name + ".png'/>";
    };

    return Instructions;

  })();

}).call(this);

/*
//@ sourceMappingURL=instructions.map
*/
